//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspMvcEf.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Test> Test { get; set; }
        public virtual DbSet<Test_Db> Test_Db { get; set; }
        public virtual DbSet<Test_Group> Test_Group { get; set; }
        public virtual DbSet<Test_Group_Ref> Test_Group_Ref { get; set; }
        public virtual DbSet<Test_Result> Test_Result { get; set; }
        public virtual DbSet<Test_Schedule> Test_Schedule { get; set; }
        public virtual DbSet<Test_Type> Test_Type { get; set; }
        public virtual DbSet<Test_Url> Test_Url { get; set; }
        public virtual DbSet<Test_User> Test_User { get; set; }
    }
}
