//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspMvcEf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test_Schedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Test_Schedule()
        {
            this.Test_Result = new HashSet<Test_Result>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Test_Group_Id { get; set; }
        public Nullable<System.DateTime> Time_Start { get; set; }
        public Nullable<int> Flag_Start { get; set; }
        public Nullable<int> Flag_Stop { get; set; }
        public int Test_Url_Id { get; set; }
        public int Test_Db_Id { get; set; }
    
        public virtual Test_Db Test_Db { get; set; }
        public virtual Test_Group Test_Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Test_Result> Test_Result { get; set; }
        public virtual Test_Url Test_Url { get; set; }
    }
}
