//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspMvcEf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test_Group_Ref
    {
        public int Id { get; set; }
        public int Test_Id { get; set; }
        public int Test_Group_Id { get; set; }
    
        public virtual Test Test { get; set; }
        public virtual Test_Group Test_Group { get; set; }
    }
}
